kind: pipeline
type: docker
name: docker-compose-deploy

steps:
  - name: build
    image: golang:1.23
    commands:
      - make build
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go

  - name: check-fmt
    image: golang:1.23
    commands:
      - make fmt
      - git diff --exit-code
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go

  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - make lint
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go

  - name: wait-for-redis
    image: atkrad/wait4x
    commands:
      - wait4x tcp redis:6379 -t 30s
    depends_on:
      - redis

  - name: wait-for-rabbitmq
    image: atkrad/wait4x
    commands:
      - wait4x tcp rabbitmq:5672 -t 30s
    depends_on:
      - rabbitmq

  - name: test
    image: golang:1.23
    environment:
      REDIS_HOST: redis
      BROKER_HOST: rabbitmq
    commands:
      - make test
    depends_on:
      - build
      - wait-for-rabbitmq
      - wait-for-redis
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go

  - name: dockerize
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      repo: localhost:8091/thek4n/paste
      tags:
        - latest
        - ${DRONE_TAG}
      dockerfile: Dockerfile
      registry: localhost:8091
      insecure: true
      build_args:
        - APP_VERSION=${DRONE_TAG}
    depends_on:
      - build
      - check-fmt
      - lint
      - test
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    when:
      event:
        - promote
      target:
        - production
        - development
      ref:
        - refs/tags/*

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.50.5
      username: thek4n
      key:
        from_secret: ssh_key
      port: 22
      script:
        - |
          cd "/home/thek4n/services/paste.thek4n.name" && \
          IMAGE_TAG="${DRONE_TAG}" docker compose up -d
    when:
      event:
        - promote
      target:
        - production
      ref:
        - refs/tags/*
    depends_on:
      - dockerize

services:
  - name: redis
    image: redis:8
    ports:
      - 6379
  - name: rabbitmq
    image: rabbitmq:3
    ports:
      - 5672

volumes:
- name: go-build-cache
  host:
    path: /tmp/go-build-cache
- name: go-mod-cache
  host:
    path: /tmp/go-mod-cache
- name: docker-socket
  host:
    path: /var/run/docker.sock
