kind: pipeline
type: docker
name: docker-compose-deploy

steps:
  - name: test-build
    image: golang:1.23
    commands:
      - ./bin/make build
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go
    when:
      event:
        include:
        - push
        - tag

  - name: check-fmt
    image: golang:1.23
    commands:
      - go fmt ./...
      - git diff --exit-code
      - go vet ./...
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go
    when:
      event:
        include:
        - push
        - tag

  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - golangci-lint -v run --timeout 5m
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go
    when:
      event:
        include:
        - push
        - tag

  - name: test
    image: golang:1.23
    environment:
      REDIS_HOST: redis-test
    commands:
      - ./bin/make test
    depends_on:
      - test-build
      - redis-test
    volumes:
      - name: go-build-cache
        path: /root/.cache/go-build
      - name: go-mod-cache
        path: /go
    when:
      event:
        include:
        - push
        - tag

  - name: dockerize
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      repo: localhost:8091/thek4n/paste
      tags:
        - latest
        - ${DRONE_TAG}
      dockerfile: Dockerfile
      registry: localhost:8091
      insecure: true
      build_args:
        - APP_VERSION=${DRONE_TAG}
    depends_on:
      - test-build
      - check-fmt
      - lint
      - test
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    when:
      event: tag

  - name: deploy
    image: alpine
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - |
        ssh -o StrictHostKeyChecking=no thek4n@192.168.50.5 \
        "cd ~/services/paste.thek4n.name &&
          docker compose up -d"

      - shred -zun 2 ~/.ssh/id_rsa
    when:
      event: tag
    depends_on:
      - dockerize

services:
  - name: redis-test
    image: redis:8
    ports:
      - 6379

volumes:
- name: go-build-cache
  host:
    path: /tmp/go-build-cache
- name: go-mod-cache
  host:
    path: /tmp/go-mod-cache
- name: docker-socket
  host:
    path: /var/run/docker.sock
