repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main, --pattern, release/.*]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: go-fmt
        name: Go formatter
        language: system
        entry: go fmt ./...
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-vet
        name: Go static analyzer
        language: system
        entry: env GOFLAGS="-tags=integration,e2e" go vet ./...
        pass_filenames: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint-full
        entry: env GOFLAGS="-tags=integration,e2e" golangci-lint run --new-from-rev HEAD --fix --timeout=5m
      - id: golangci-lint-fmt
        entry: env GOFLAGS="-tags=integration,e2e" golangci-lint fmt

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [
          "--ignore", "body-is-missing", "--contrib=CT1", "--msg-filename",
        ]
        stages: [commit-msg]
