networks:
    paste-network:

services:
  paste:
    build:
      context: .
      dockerfile: Dockerfile

    image: 'thek4n/paste'

    pull_policy: build

    container_name: 'paste'

    depends_on:
      db:
        condition: service_started

    ports:
      - 8080:80

    networks:
      - paste-network

    environment:
      REDIS_HOST: 'paste-db'

    restart: always

  db:
    image: redis
    container_name: 'paste-db'
    networks:
      - paste-network
    restart: always
